
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  " Ext.Msg": "ext/src/window/MessageBox.js",
  "Ext": "ext/src",
  "CarTracker": "app",
  "Ext.rtl.EventObjectImpl": "ext/src/rtl/EventObject.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "CarTracker.view.layout.Landing": [],
  "Ext.ux.DataView.DragSelector": [],
  "CarTracker.view.staff.List": [],
  "CarTracker.view.car.search.Window": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "CarTracker.store.option.Colors": [],
  "CarTracker.view.staff.edit.Window": [],
  "CarTracker.store.option.Features": [],
  "Ext.ux.PreviewPlugin": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "CarTracker.view.layout.Center": [],
  "CarTracker.store.option.Statuses": [],
  "Ext.ux.CellDragDrop": [],
  "CarTracker.view.car.search.Form": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "CarTracker.controller.Staff": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "CarTracker.view.layout.West": [],
  "Ext.ux.event.Recorder": [],
  "CarTracker.model.option.Position": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "CarTracker.view.car.edit.tab.Detail": [],
  "CarTracker.controller.Options": [],
  "CarTracker.model.option.Feature": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "CarTracker.model.Staff": [],
  "Ext.ux.TreePicker": [],
  "CarTracker.model.option.Status": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "CarTracker.view.car.edit.Window": [],
  "CarTracker.view.option.List": [],
  "Ext.ux.GroupTabRenderer": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "CarTracker.view.car.edit.Form": [],
  "CarTracker.store.option.Models": [],
  "CarTracker.store.option.Positions": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "CarTracker.view.car.List": [],
  "Ext.ux.GMapPanel": [],
  "CarTracker.view.Viewport": [],
  "CarTracker.model.option.Category": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "CarTracker.store.option.Categories": [],
  "CarTracker.view.car.edit.tab.Feature": [],
  "CarTracker.controller.Base": [],
  "Ext.ux.DataView.Animated": [],
  "CarTracker.store.option.Makes": [],
  "CarTracker.model.option.Base": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "CarTracker.controller.App": [],
  "CarTracker.view.layout.North": [],
  "CarTracker.view.layout.Menu": [],
  "CarTracker.ux.form.field.plugin.ClearTrigger": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "CarTracker.model.Car": [],
  "Ext.ux.RowExpander": [],
  "CarTracker.controller.Cars": [],
  "Ext.ux.event.Player": [],
  "CarTracker.model.option.Color": [],
  "CarTracker.model.Base": [],
  "Ext.ux.ToolbarDroppable": [],
  "CarTracker.model.option.Model": [],
  "Ext.ux.event.Maker": [],
  "CarTracker.store.Cars": [],
  "CarTracker.view.staff.edit.Form": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "CarTracker.model.option.Make": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "CarTracker.ux.form.field.RemoteComboBox": [],
  "CarTracker.store.Staff": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "CarTracker.view.layout.Landing": [
    "widget.layout.landing"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "CarTracker.view.staff.List": [
    "widget.staff.list"
  ],
  "CarTracker.view.car.search.Window": [
    "widget.car.search.window"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "CarTracker.store.option.Colors": [
    "store.option.color"
  ],
  "CarTracker.view.staff.edit.Window": [
    "widget.staff.edit.window"
  ],
  "CarTracker.store.option.Features": [
    "store.option.feature"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "CarTracker.view.layout.Center": [
    "widget.layout.center"
  ],
  "CarTracker.store.option.Statuses": [
    "store.option.status"
  ],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "CarTracker.view.car.search.Form": [
    "widget.car.search.form"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "CarTracker.controller.Staff": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "CarTracker.view.layout.West": [
    "widget.layout.west"
  ],
  "Ext.ux.event.Recorder": [],
  "CarTracker.model.option.Position": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "CarTracker.view.car.edit.tab.Detail": [
    "widget.car.edit.tab.detail"
  ],
  "CarTracker.controller.Options": [],
  "CarTracker.model.option.Feature": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "CarTracker.model.Staff": [],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "CarTracker.model.option.Status": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "CarTracker.view.car.edit.Window": [
    "widget.car.edit.window"
  ],
  "CarTracker.view.option.List": [
    "widget.option.list"
  ],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "CarTracker.view.car.edit.Form": [
    "widget.car.edit.form"
  ],
  "CarTracker.store.option.Models": [
    "store.option.model"
  ],
  "CarTracker.store.option.Positions": [
    "store.option.position"
  ],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "CarTracker.view.car.List": [
    "widget.car.list"
  ],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "CarTracker.view.Viewport": [],
  "CarTracker.model.option.Category": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "CarTracker.store.option.Categories": [
    "store.option.category"
  ],
  "CarTracker.view.car.edit.tab.Feature": [
    "widget.car.edit.tab.feature"
  ],
  "CarTracker.controller.Base": [],
  "Ext.ux.DataView.Animated": [],
  "CarTracker.store.option.Makes": [
    "store.option.make"
  ],
  "CarTracker.model.option.Base": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "CarTracker.controller.App": [],
  "CarTracker.view.layout.North": [
    "widget.layout.north"
  ],
  "CarTracker.view.layout.Menu": [
    "widget.layout.menu"
  ],
  "CarTracker.ux.form.field.plugin.ClearTrigger": [
    "plugin.cleartrigger"
  ],
  "Ext.ux.grid.menu.RangeMenu": [],
  "CarTracker.model.Car": [],
  "Ext.ux.RowExpander": [],
  "CarTracker.controller.Cars": [],
  "Ext.ux.event.Player": [],
  "CarTracker.model.option.Color": [],
  "CarTracker.model.Base": [],
  "Ext.ux.ToolbarDroppable": [],
  "CarTracker.model.option.Model": [],
  "Ext.ux.event.Maker": [],
  "CarTracker.store.Cars": [
    "store.car"
  ],
  "CarTracker.view.staff.edit.Form": [
    "widget.staff.edit.form"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "CarTracker.model.option.Make": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "CarTracker.ux.form.field.RemoteComboBox": [
    "widget.ux.form.field.remotecombobox"
  ],
  "CarTracker.store.Staff": [
    "store.staff"
  ]
});
